# https://github.com/elastic/kibana-docker
#FROM docker.elastic.co/kibana/kibana-oss:6.1.0
FROM docker.elastic.co/kibana/kibana-oss:6.3.1
# 5.6.3 is not offcially available: https://www.docker.elastic.co/#
# Note kibana-oss not available prior 6.0 https://www.elastic.co/guide/en/kibana/5.6/_pulling_the_image.html
# https://github.com/deviantony/docker-elk/tree/e8c1fc2d401cdb7d933aa1d704a5c319367b5927/elasticsearch
#FROM docker.elastic.co/kibana/kibana:5.6.3

# Add your kibana plugins setup here
# Example: RUN kibana-plugin install <name|url>
